### ISSUE TITLE
[BE] HikariCP Connection 상태에 대한 로그 필요

### ISSUE THREAD

**Issue by Gomding** [woowacourse-teams/2021-nolto#689]
## 기능 요구 사항
application.yml 에 추가해주세요

```
logging: 
  level: 
    com.zaxxer.hikari.HikariConfig: INFO 
    com.zaxxer.hikari: INFO
```
